apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/gosec-sast-scan-code@v1
        name: Run gosec (SO)
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Run Sonarqube
        with:
          language: LANGUAGE_GO
      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Run Findsecbugs
