apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/checkout@v1
        name: checkout-source-code
      - uses: cloudbees-io/gosec-sast-scan-code@v1
        name: Gosec scan
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: SonarQube Scan
        with:
          language: LANGUAGE_GO
